In [23]:
import datetime
import os
from pathlib import Path
import pandas as pd

from tlo.analysis.life_expectancy import get_life_expectancy_estimates
from tlo import Date, Simulation, logging, util
from tlo.analysis.probability_premature_death import get_probability_of_dying_before_70

In [24]:
results_folder = Path("/Users/rem76/PycharmProjects/TLOmodel/outputs/tbh03@ic.ac.uk/long_run_all_diseases-2024-05-31T160939Z/")

In [22]:
get_life_expectancy_estimates(results_folder,target_period=(datetime.date(2010, 1, 1), datetime.date(2020, 12, 31)), summary = False)

draw          0                                                         \
run           0          1          2          3          4          5
sex
M     58.854789  59.182485  58.462134  59.019825  58.879304  59.704822
F     63.282462  62.338287  63.302513  63.005595  63.551367  63.089974

draw
run           6          7          8
sex
M     58.635976  58.749800  58.888191
F     63.343861  63.088528  62.399674

In [ ]:
get_life_expectancy_estimates(results_folder,target_period=(datetime.date(2010, 1, 1), datetime.date(2020, 12, 31)), summary = False)

In [26]:
get_probability_of_dying_before_70(results_folder,target_period=(datetime.date(2010, 1, 1), datetime.date(2020, 12, 31)), summary = False, max_age = 80)

draw         0                                                              \
run          0         1         2         3         4         5         6
sex
M     0.597017  0.579700  0.597767  0.591821  0.602394  0.617965  0.589396
F     0.473033  0.485873  0.465402  0.478161  0.461935  0.460389  0.471456

draw
run          7         8
sex
M     0.576299  0.590346
F     0.495766  0.495891